solanum-ircd/solanum

include/s_serv.h
ircd/s_serv.c
modules/m_cap.c
modules/m_sasl.c
modules/m_starttls.c

More conservative approach to #11. We decided on IRC that it wasn't possible to send multiple lines of CAP LS to clients that don't request 302 without breaking some of them, so this change just puts the capabilities we think are important first in the list.

CAP <3.2 multiline compatibility

---

help/opers/index
help/opers/testkline
modules/m_testline.c

Like /testline, but doesn't report on I-lines or resvs or care if the former are missing.

Add /testkline

---

doc/reference.conf
extensions/helpops.c

So it's incompatible with IP cloaking modules that use +h. We can choose between them. Or maybe just throw the IP cloaking modules out...

helpops: change umode char to h

---

modules/m_stats.c

Every other use of RPL_STATSDEBUG follows the format: `<letter> :<text>`
This case appeared to slip through because it's two-word argument is encoded
in a single `->data` buffer.

Combine stats A output parameters

---

modules/core/m_message.c

We're doing this as a globally propagated snote from the source server rather than something local because overriding message propagation is more complicated than just using snote propagation as-is.

m_message: global snote when massnotice is used

---

.gitignore
ircd/match.c
tests/Makefile.am
tests/TESTS
tests/match1.c

The algorithm we're using gets stuck if it has a ? and can only see a * to feed to it, even if it could skip over that * and consume a character following it. Remedy this by rearranging the input so * always precedes ? in runs of wildcards, so when we're matching ? we know we can skip things.

Fix a corner case of superset matching

---

.travis.yml
include/client.h
ircd/parse.c
tests/client_util.c

There's one that fails, which I'm remedying by adding a local client flag to shut it up. If it happens more often we might think about a generic mechanism for tests to silence/expect assertions.

Actually run tests with assertions enabled

---

.gitignore
extensions/chm_operonly_compat.c
extensions/chm_quietunreg_compat.c
extensions/chm_sslonly_compat.c
include/channel.h
include/chmode.h
ircd/chmode.c
tests/Makefile.am
tests/TESTS
tests/chmode1.c
tests/chmode1.conf

The previous behaviour did one access check for a query, and then another one if you tried to set something, with the result that you couldn't see +eI lists with `MODE #foo e`, but you could by prefixing with a +: `MODE #foo +e`. Also you'd send an override snote for a query you could have done without override.
Most of this change is just making things more consistent; currently I've also got an override change in here to prevent using it to view +eI lists at all, but there's an argument to be had about how you should do that.
As a bonus, doing the parsing properly means we can restore the behaviour of `MODE #foo b x!y@z` (which once banned x!y@z, then didn't because override reauthorization hack).
I've been fairly conservative about rejecting invalid mode commands we can now detect …

Restructure channel mode handling, make it interact consistently with override

---

help/opers/stats
modules/m_stats.c

`s` and `S` were both used for ssld stats, but only `S` was documented, so I'm taking `s`. You can't stop me!

Add /stats s to list secure blocks

---

ircd/s_serv.c

as per #46 - netjoined servers end up with reversed ban lists.
this is due to `add_id()` doing left appends, which means local queries of ban lists do newest-to-oldest, but once we send the list newest-to-oldest to a server we're bursting, they do left appends newest-to-oldest, making the their list oldest-to-newest.

iter lists backwards when sending BMASK

---

extensions/m_findforwards.c
include/messages.h
include/send.h
ircd/channel.c
ircd/s_serv.c
ircd/send.c
modules/m_cap.c
modules/m_monitor.c
modules/m_names.c
modules/m_privs.c
modules/m_whois.c
tests/Makefile.am
tests/send_multiline1.c
tests/send_multiline1.conf

This will greatly simplify and deduplicate code in various places, like CAP LS/LIST, NAMES, and WHOIS channel lists.
Fixes #16

API for automatically splitting long messages in places where spec allows/requires it

---

ircd/send.c

A netwide snote eventually calls into this function again with the same server as has already been determined is over its sendq.  Mark the link dead before sending the snote to avoid infinite recursion.

send: fix infinite recursion in _send_linebuf

---

ircd/chmode.c
modules/core/m_mode.c

We were ending the flood grace period for any channel mode command other than `MODE #foo [bq]` by means of a hardcoded check. I've moved that to after we parse the mode string, so we can correctly identify all requests to change modes and end the grace period on exactly those.
It would have been entirely possible to move the check even further down and flood_endgrace on only mode commands that *actually* change modes, but I don't like the idea of making it sensitive to external conditions.

chmode: end the grace period more intelligently

---

NEWS.md
doc/ircd.conf.example
doc/reference.conf
help/opers/wallops
include/s_newconf.h
modules/m_wallops.c

Split oper:wallops right from oper:mass_notice. Update documentation and
examples to grant oper:wallops everywhere oper:mass_notice was granted.
closes #103

wallops: require new oper:wallops right

---

doc/reference.conf
librb/src/openssl.c
librb/src/openssl_ratbox.h

The OpenSSL developers decided, during the OpenSSL 1.1.1 development phase, to use a different API and different set of lists for TLSv1.3 ciphersuites, than for every TLS version preceeding it.
This is stupid, but we have to work with it.
This commit also improves configuration fault resilience. The reason is that if you don't pass any valid old-style ciphersuites, OpenSSL will not negotiate an older protocol at all. However, when they implemented the new API, they decided that lack of any valid ciphersuites should result in using the defaults. This means that if you pass a completely invalid ciphersuite list (like "foo"), OR if you pass a TLSv1.2-only ciphersuite list, TLSv1.3 continues to work. This is not mirrored; passing a TLSv1.3-only ciphersuite list will break TLSv1.2 and below. …

OpenSSL: Support configuration of TLSv1.3 ciphersuites

---

include/hostmask.h
ircd/hostmask.c
modules/m_kline.c

I've also made /kline delete any matching temporary non-propagated K-lines (as effectively happened for propagated ones already) since otherwise this would make it very easy to add duplicates, and made /unkline able to delete multiple matches—while I don't know that there's any way to add unlimited duplicate K-lines, one can add two (a propagated K-line and a longer local K-line, for instance).
The propagated K-line logic already handles extensions adequately; `replace_old_ban` will ensure they win out over the extendee. You just couldn't tell /kline to do them until now.

Allow temporary K-lines to extend shorter ones

---

ircd/supported.c

This was introduced in commit bde6442c47 but the rationale for it is pretty shaky. 
No other non-Charybdis-derived servers send it and the features the original commit claims it can be used to detect all have
their own methods of detection. 
The concept of "core capabilities" and versioned releases was also dropped by IRCv3 many years ago in favour of living specifications.

Remove the CLIENTVER 005 token.

---

librb/src/radixtree.c

STATE_CUR(state) = NULL causes rb_radixtree_foreach_next() to fail,
instead set both state pointers to the same address.
Closes #168.

librb: radixtree: fix iteration restarting

---

librb/src/mbedtls.c

Line 390 uses 'data', which can get pointed to inside of der_pubkey at line 386.  However, der_pubkey was defined locally inside the if at line 374.  Move the variable outside of the if so that  it doesn't fall out of scope.

librb mbedTLS: der_pubkey is used out of scope

---

modules/m_sasl.c

Further to our implementation of the concept of "secure origins", we can indicate to services that the client is connected securely, rather than just that the client is using TLS. For example, connections from the local host (from the IRCd's perspective) can be considered secure against eavesdropping.
Allow this to factor into services' decision on whether to allow an SASL negotiation or not. Atheme currently assumes this means the client is using TLS, but I have changed that in atheme/atheme@412d50103c1d8c2a

modules/m_sasl.c: use IsSecure() instead of IsSSL()

---

extensions/Makefile.am
extensions/invex_regonly.c
extensions/m_invex_regonly.c

This module allows +I to be used to bypass +r (registered only) as well as +i (invite only).

Port m_invex_regonly from ircd-seven

---

ircd/msgbuf.c

Given cache->overall_capmask was already computed, but not used, I haved a feeling that this was always planned but the original implementers forgot about it. Without this change, messages to large channels with diverse clients consistently cause _many_ cache evictions; with it they never do.
Reviewers: the `caps` parameter we're modifying eventually makes its way to `msgbuf_unparse_tags`, where it's &ed with `msgbuf->tags[foo].capmask`, the same field whose | makes up overall_capmask. Given that, I think any bits in caps that aren't in overall_capmask will never be used anyway.

msgbuf: use only relevant caps for the cache key

---

help/users/umode

currently, this space breaks rendering in at least one client:
Quassel issue: https://bugs.quassel-irc.org/issues/1733

remove trailing space from umode help file

---

README.md
librb/src/commio.c

- The official Sun/Oracle solution is to use the extendedFILE(5)
mechanism, which works around the limitation.
https://docs.oracle.com/cd/E18752_01/html/816-5175/extendedfile-5.html
- Add a quick HOWTO to the README.md

Remove unneeded ugly hack for 32-bit Solaris

---

modules/core/m_join.c

ERR_USERONCHANNEL when following a forward is missing a param

---

modules/m_sasl.c

The current behavior creates a huge load on netjoin as thousands of already authenticated clients all try to reauthenticate at once for no particular benefit.

Stop announcing SASL cap changes on services split/join

---

doc/ircd.conf.example
doc/reference.conf
ircd/s_user.c

```
:copper.libera.chat NOTICE l :*** Notice -- You need to identify via SASL to use to use this server.
ERROR :Closing Link: ranger.zpld.me (You need to identify via SASL to use to use this server.)
```

fix typo in `sasl_only_client_message`

---

modules/m_etrace.c

When running `/etrace <nick>` against a local user, the "end of trace" numeric is not sent to the client. This numeric is sent in all other circumstances (such as when running `/etrace <nick>` against a remote user), so send it when executing locally as well for consistency.

Send RPL_ENDOFTRACE on local /etrace

---

ircd/packet.c

This function has a static forward-declaration, and is not used outside this compilation unit. However, the definition was non-static. Fix this.

ircd/packet.c: make function definition consistent with declaration

---

extensions/chm_nonotice.c

chanserv currently cannot notice `VERBOSE` channels that are `+T` and it feels needless to check this on every single server of the network

don't subject remote users to chm_nonotice

---

help/opers/cmode
help/opers/umode
help/users/umode

The old descriptions might be interpreted as meaning that +u enables
server-side filtering.

Remove ambiguity in descriptions +u

---

ircd/chmode.c

I think this was always pretty questionable. You can set redundant bans in various ways anyway, and preventing all of them would only make the situation worse, as wide temporary bans would destroy narrow permanent ones, for example.
Fixes #321, fixes #322

Remove the subset ban restriction

---

authd/providers/opm.c

This header defines the TCP_NODELAY flag, which this compilation unit uses.
Other C libraries implicitly include this header from some other header we are using (I have not investigated which), but musl's system headers do not, which breaks building on musl.
Reported-by: 0x5c <dev@0x5c.io>

authd/providers/opm.c: include <netinet/tcp.h>

---

doc/reference.conf
include/messages.h
include/s_conf.h
ircd/hostmask.c
ircd/newconf.c
ircd/s_conf.c
modules/m_stats.c
modules/m_testline.c

This would make it easy to see _why_ we have so many I lines and to group them back together to a single auth block both with manual queries and also for consumption by automated tooling.

Add description parameter to auth blocks

---

ircd/version.c.SH

While working on reproducible builds for openSUSE, I found that
our `solanum` package varied even when building in clean VMs
with as little non-determinism as possible.
This was because of variations in the `generation` value in version.c
```diff
+++ solanum-0~ch560/ircd/version.c.last
@@ -25,7 +25,7 @@
#include "serno.h"
#include "stdinc.h"
-const char *generation = "6";
+const char *generation = "5";
const char *creation = "1653004800";
const char *ircd_version = PATCHLEVEL;
const char *serno = SERNO;
```

Normalize generation for reproducible builds

---

authd/res.c
extensions/extb_extgecos.c
ircd/chmode.c
ircd/newconf.c
ircd/reject.c
ircd/s_user.c
librb/src/event.c
modules/m_map.c
modules/m_scan.c

The first commit fixes an actual bug (though since `static char buf[BANLEN * MAXMODEPARAMS];` is 780 bytes, I'm pretty sure it's impossible to hit). The second commit just uses sizeof where possible and can be dropped. Some instance are off by one, but by under counting size not over counting it.

Snprintf sizeof

---

ircd/ircd.c
librb/src/unix.c
modules/m_stats.c

- getexecname(3) returns const char *
- pid_t is long

Illumos fixes

---

ircd/chmode.c

With this
```
MODE #test +b foo!*@*
MODE #test -b Foo!*@*
```
outputs `MODE #test -b foo!*@*` rather than `MODE #test -b Foo!*@*` which makes state tracking easier.

chmode: Use original string when removing a mask

---

extensions/m_webirc.c

per the [IRCv3 WEBIRC](https://ircv3.net/specs/extensions/webirc) spec:
> If the connection fails to the IRC server, the WebIRC gateway MUST return an ERROR with an appropriate message and terminate the connection.

ERROR instead of NOTICE for failed WEBIRC

---

ircd/s_serv.c

Due to [1], linking with SCTP sometimes does not multi-home correctly. This is triggered by the `rand()` on the lines immediately above these.
The `connect{}` blocks already support an `aftype` parameter to instruct IRCd to prefer IPv4 or IPv6. This commit additionally ensures that the other structure is always populated with the other address (if any) if this parameter is specified.
This will allow SCTP server-linking users to work around the bug and ensure that it always multi-homes by setting `connect::aftype` to IPv4. Without this commit, that would cause Solanum to not include the IPv6 addresses (if any) in the connect block in its SCTP setup.
If there isn't a valid IP address in the other sockaddr, this should be of no consequence, because it will not be used by `rb_connect_tcp()`, …

serv_connect(): ensure both sa_bind[]/sa_connect[] are always populated

---

extensions/chm_regmsg.c
include/messages.h

sendto_one_numeric already includes the nick, so there's no need to duplicate it. OFTC does not.

chm_regmsg: don't duplicate nick in 415

---

configure.ac
librb/configure.ac
librb/src/commio.c

Unlike Linux, Solaris, and Illumos (and probably others), the 2 BSDs that still support SCTP didn't put SCTP into its own library; they put it into libc.
They, unlike Linux, don't set `SOL_SCTP` for us. The official method appears to be calling `getprotobyname("sctp")` & `endprotoent()`, with `getprotobyname()` returning a struct that has a `p_proto` entry. This all reads from `/etc/protocols`. However, SCTP is assigned 132 by IANA, so it's 132 everywhere, so I just set `SOL_SCTP` to 132 if it's not already set.

Fix SCTP support on FreeBSD & NetBSD

---

configure.ac
librb/configure.ac

The spaces surrounding the = is bad syntax, which causes the shell to try to
execute 'assert'.
Granted, all of this is just cosmetic, as the only use of $assert seems to be
in the echo at the end of the configure run.

Fix assert = hard assignments

---

librb/src/crypt.c

This code is doing `(foo - (char*)0)` to convert `foo` from a pointer value into a numeric value. Unfortunately, this is undefined behaviour, which clang-14 is now warning about [1].
Cast to uintptr_t instead. Same result, but well-defined.
[1] cf. commit 0302f1532b66e9d09b70

librb/src/crypt.c: rb_sha256_crypt_r: avoid UB pointer math

---

include/client.h
include/s_newconf.h
ircd/newconf.c
ircd/s_newconf.c
librb/src/openssl.c
modules/m_challenge.c

cf. #357
Edited by @aaronmdjones:
- Correct some data types and casts
- Minor style fixups (e.g. we put `*` on the variable name not the type)
- `librb/src/openssl.c`:
- Defer call of `BIO_free(3ssl)` to the end of the conditional block to avoid having calls to it in multiple paths
- Check the return value of `SSL_CTX_set0_tmp_dh_pkey(3ssl)` because if it fails then we must use `EVP_PKEY_free(3ssl)` to avoid a memory leak
This could fail if, for example, the user supplied DSA parameters in the DH parameters file instead.
- `ircd/newconf.c`:
- Check whether `OSSL_DECODER_CTX_new_for_pkey(3ssl)` was able to parse the given CHALLANGE public key as a valid RSA public key, and then check whether `OSSL_DECODER_from_bio(3ssl)` actually loads it successfully
- `ircd/s_newconf.c`:
- Use …

OpenSSL 3.0 compatibility

---

configure.ac
include/stdinc.h
ircd/ircd.c
librb/acinclude.m4
librb/configure.ac
librb/include/commio-int.h
librb/src/arc4random.c
librb/src/commio.c
librb/src/epoll.c
librb/src/linebuf.c
librb/src/poll.c
librb/src/rb_lib.c
librb/src/sigio.c
librb/src/tools.c
librb/src/unix.c
ssld/ssld.c
wsockd/wsockd.c

Remove portability code for systems that don't follow at least SUSv3.
This fairly closely aligns with ISO C99, which solanum already requires.

Remove ancient portability code

---

extensions/README

the unsupported directory [was removed](https://github.com/solanum-ircd/solanum/blob/main/NEWS.md#misc-6) by charybdis a while ago

remove old reference to the unsupported directory from extensions readme

---

librb/src/arc4random.c

For some reason, compiling failed, and GCC said a semicolon was needed here. All tests succeeded locally with a semicolon (make check).
GCC version:
```
gcc (GCC) 11.3.0
```
flex version:
```
flex 2.6.4
```
bison version:
```
bison (GNU Bison) 3.8.2
```
sqlite version:
```
3.38.5 2022-05-06 15:25:27 78d9c993d404cdfaa7fdd2973fa1052e3da9f66215cff9c5540ebe55c407d9fe
```
autoconf version:
```
autoconf (GNU Autoconf) 2.71
```
automake version:
```
automake (GNU automake) 1.16.5
```
cmake version:
```
cmake version 3.22.3
```
pkg-config version:
```
0.29.2
```
libtool version:
```
libtool (GNU libtool) 2.4.7
```
Latest commit:
```
01fb744c405792dd3f0859a53f74cd4cb5fd166f
```
column version:
```
column from util-linux 2.37.4
```
autoreconf version:
```
autoreconf (GNU Autoconf) 2.71
```
Output …

Add semicolon to fix a compile error in librb/src/arc4random.c

---

extensions/chm_regmsg.c

This is a self-contained fix to chm_regmsg to make it work with +z, while maintaining the custom error message for -z channels.
The ideal fix might be to change the rest of the code to allow for custom errors to be sent (and suppress the standard ones in that case), but until we can work that out this change makes things work and can be (re-)loaded as a single module.

Make +R play nicely with +z

---

NEWS.md
modules/m_sasl.c
tests/sasl_abort1.c

This doesn't make sense in a world where post-registration SASL is allowed, and should fix one case of an annoying login desync that's seen in the real world.
Specifically, when a client sends its final AUTHENTICATE and Atheme receives it, it sends an SVSLOGIN for that client. If the client sends us its CAP END *before* we see the SVSLOGIN, the implicit abort will try to abort the SASL session that's already succeeded.
Atheme interprets this as an instruction to forget about the successful SASL session; you'll connect unidentified. But it's already sent SVSLOGIN, which will log the client in ircd-side, causing ircd and services views to differ until the user authenticates again manually.
I think allowing a SASL session to be aborted when it has already succeeded is an Atheme bug, and it …

m_sasl: Remove implicit abort on registration

---

librb/src/helper.c

Instead of arbitrarily limiting it to 256.  This avoids an issue with 
busy authds "running out" of fds because librb says no more.

librb/helper: pass our fd limit to the child

---

extensions/umode_hide_idle_time.c
help/opers/umode
help/users/umode
modules/m_whois.c

If the user performing a WHOIS has hidden their idle time (is umode `+I`), also prevent them from seeing other user's idle times,  even if said users are not themselves umode `+I`.
Suggested-by: @Unit193

extensions/umode_hide_idle_time: mask times for hidden sources

---

ircd/authproc.c

Ensure we deallocate the nodes created by the first loop, and zero out the authd data after removing them from the authd clients dict. The `authd_abort_client()` function already does the latter, so just call that instead of `authd_free_client()`.

timeout_dead_authd_clients(): fix memory leak and order of operations

---

modules/m_grant.c

Although this can't happen without a broken server on the network, there's no need to crash the whole network if it does.

Don't crash on receiving GRANT from a server

---

include/s_newconf.h
modules/m_stats.c

Null "compress" handler left as-is in newconf.c

Remove the unused COMPRESSED flag and stats handler

---

include/authproc.h
ircd/authproc.c
ircd/s_user.c
modules/m_stats.c

authd child processes are only told about configured DNSBLs when the configuration is being parsed.
This is bad, because when authd crashes or is killed, IRCd will restart it, but will not tell it about any configured DNSBLs until IRCd is next rehashed.
We already have a dictionary that stores configured DNSBLs (for hit statistics for `STATS n`), so store the additional needed fields in that structure, and loop over that dictionary's entries when authd is restarted, sending the fields just as if the configuration were being reloaded.
Reported-By: @Unit193

authd: fix crash/restart breaking DNSBL lookups

---

ircd/authproc.c

Fixes fbc97166a6e455f5cccf
Closes #396

ircd/authproc.c: avoid crash on lack of any configured DNSBLs

---

modules/um_callerid.c

Before splitting things out into hooks, umode +Rg would only notify the recipient if the sender satisfied +R. This restores that behavior by making the +g hook happen after +R.

um_callerid: increase hook priority to restore +Rg behavior

---

ircd/chmode.c

This fixes an issue where a ban could be set, hit, and cleared all in the same second, and the affected client would still be cached as banned  because the bants hadn't actually changed.

chmode: ensure bants increases on banlist change

---

doc/connecting-servers.rst

Atheme has had a [protocol module](https://github.com/atheme/atheme/blob/master/modules/protocol/solanum.c) designed specifically for Solanum for some time now that includes proper support for new IRCd features.

doc/connecting-servers: update example atheme protocol module

---

ircd/modules.c

This allows explicitly loading a module in the config so it's available for later config items that might need it, and skips the double load when main loads all modules, which would cause errors

modules: quietly succeed at loading a module if already loaded

---

extensions/extb_extgecos.c

This commit returns `$x`'s old behavior as long as the mask does not contain a `#`, otherwise it uses the new behavior that supports CIDR notation.
This fixes `$x:*badword*` not matching realnames containing "badword".

extensions/extb_extgecos: Fix breakage

---

ircd/s_conf.c
librb/include/rb_commio.h
librb/src/commio.c
librb/src/export-syms.txt

Fixes bug/probable regression introduced by 0ab6dbbc651ddd1c26cb7baa6e6cf86890a4abd2
rehash() closes listeners. If we happen to get a single epoll() result that wants to first rehash and then accept a connection, the epoll info will point to a freed rb_fde_t. Other selectors should have similar problems, but we didn't investigate that.
rb_fde_ts are normally batched up and freed outside the event processing, but as of the above commit close_listeners() screws that up by closing pending FDs immediately in order to create new listeners.
I think it might be a bit better to revert this behaviour and simply not close listeners if we are going to open new ones over them, but have opted for the smallest reasonable change I can think of.

Delay rehashing until we're not processing events

---

include/client.h
ircd/client.c
ircd/s_user.c
modules/core/m_nick.c
modules/m_services.c

This allows reusing this function for other uses that just need to remove this client from others' accept lists on nick change and not have duplicates of this code everywhere

client: refactor del_all_accepts to allow skipping own accept list

---

include/reject.h
ircd/listener.c
ircd/reject.c

This is in furtherance of commit 3fdf26aa19628d5e12a3 which added functionality to reply with a TLS record layer alert for D-Lined TLS clients. It turns out that there are other plaintext error messages in this same function that should receive the same treatment.
Also move another error string to a variable and use a compile-time optimised-out strlen for it too, to use the same approach as an existing error string.

ircd/listener: return a fatal TLS alert for early rejected TLS clients

---

modules/core/m_modules.c

Commit 41390bfe5fa3895b8dee fixed a bug whereby the processing of a `MODRESTART` command could result in a crash. The approach taken in this fix was to defer the reloading of all modules so that the call stack does not contain functions located in modules that are being reloaded. It did this by scheduling a one-shot timer event for 1 second in the future, in the absense of any better deferral mechanism at the time. Timers are processed by the event loop, which is core to IRCd and cannot be reloaded.
Commit 59ea3c6753e80d051b20 introduced a mechanism to defer the execution of a function until all events have been processed by the event loop, in order to fix a `REHASH` bug that could result in a crash due to closing and reopening listener sockets with a pending socket connection event to …

MODRESTART/MODRELOAD: Defer reloading more quickly

---

doc/reference.conf

Fixes: 4d8088c386c23049fcfe ("Allow auth{} to apply extra umodes")

doc/reference.conf: document the auth::umodes configuration option

---

modules/m_whois.c

Prior to this commit, `RPL_WHOISCHANNELS` always contained all channel membership prefixes, even when the client had not enabled the multi-prefix capability. This behaviour predates available commit history. Other ircds only return the highest prefix, as prescribed by the RFCs.
(Thanks to @fireonlive for helping me test this!)

Fix WHOIS reply not respecting a lack of the multi-prefix capability

---

modules/m_whois.c

The original behavior has existed since before git history, and has no known impact on clients that exist today.
This reverts commit 746ced2

m_whois: restore original multi-prefix behavior

---

ircd/s_conf.c
ircd/s_user.c

This ensures [ won't appear in the various rejection snotes, and invalid username characters only appear in the snote announcing their rejection.
Supersedes #433 and #381
Fixes #334

Sanitize username early, and early reject invalid ones

---

librb/src/openssl.c

We're only using x509 certificates as a carrier for public keys. Expiration dates are useless here because revocation is done in NickServ by removing fingerprints. We don't rely on time-bounded CA signature like common PKI.
Expiration dates only serve to confuse and lock out legitimate users.

Accept expired certificates

---

modules/m_stats.c

These format specifiers were all wrong. Use the right ones. Musl time_t is always 64 bits, so promote all rb_current_time usage to 64 bits.      
Fixes #437

m_stats: correct format specifiers and types

---

modules/m_admin.c
modules/m_info.c
modules/m_motd.c
modules/m_stats.c
modules/m_trace.c

The modules where removed in https://github.com/solanum-ircd/solanum/pull/40
This just removes leftover code.

modules: remove unused spy code.

---

include/s_newconf.h
ircd/s_user.c

The oper_conf flags are a different set of flag
bits than the client flags. The oper flags are
hardcoded to have ENCRYPTED set which is the same
flag as PINGSENT on the client struct. This can
cause a client to timeout if the last thing it
does is oper up.

Don't set the oper flags on client

---

doc/ircd.conf.example
doc/oper-guide/config.rst

7c7065b0 introduced class::max_autoconn configuration parameter. However, this parameter was never added to config.rst and the example config. This commits adds them there as well.

Add max_autoconn to documentation

---

extensions/createauthonly.c
extensions/createoperonly.c
include/hook.h
modules/core/m_join.c

`hook_data_can_create_channel` includes the name of the channel being created, which is necessary for any non-trivial restriction of channel creation as well as sending correct error messages.
The new hook data matches the layout of the previous hook data, taking advantage of a disused pointer field in `hook_data_client_approval` as used by callers of the hook (`m_join`).
There are two in-tree extensions that use can_create_channel. This PR doesn't currently attempt to change either of them to benefit from the new functionality.

Add dedicated hook data type for can_create_channel

---

librb/src/openssl.c

cf. #453 
I have also tested MbedTLS; it doesn't care as-is.
I am unable to test GNUTLS; I cannot even connect an IRC client to IRCd. It simply immediately closes the connection after ChangeCipherSpec is sent to the client. I will look into this some more.

Permit TLS client certificates without the clientAuth EKU

---

tests/serv_connect1.c

GCC 15 fails to compile this unit, erroring out on providing 6 arguments to a function that is declared to take none.
Reported-By: Unit193

tests/serv_connect1: use proper function prototype for rb_connect_tcp

---

modules/m_rehash.c

The current situation is that one needs `oper:remoteban` privilege in order to send a remote REHASH of any type.  Hilariously, this includes re-reading the HELP files, re-reading `/etc/resolv.conf`, re-reading the MOTD and OMOTD files, or restarting `ssld` -- things that have nothing to do with banning.
In days gone by, servers would be unable to check the privileges of remote opers.  This is no longer the case since commit ed3ca2ff16a1dc921d90.
I note that the `rehash_ssld()` function already includes a possibly-remote privilege check for `oper:admin` since commit fbd3e77eac3889b95855 which pre-dates bursting of operators and their privsets.

REHASH: Move privilege check for oper:remoteban to appropriate places
