solanum-ircd/solanum

modules/m_cap.c

Spec doesn't really allow multiline here, so don't use it

m_cap: simplify cap_req, remove multiline

---

modules/m_info.c

Notably, it's now possible to run oper /info with asan.

Make m_info a bit less terrible

---

Makefile.am
help/Makefile.am
tests/Makefile.am

Fix a bunch of small problems pointed out by @unit193 on IRC

Clean up some build untidiness

---

doc/reference.conf
include/s_conf.h
ircd/newconf.c
ircd/s_conf.c
modules/m_challenge.c
modules/m_grant.c
modules/m_info.c
modules/m_oper.c

add ConfigFileEntry.oper_secure_only, to require TLS to oper up

---

include/hook.h
include/privilege.h
include/s_user.h
ircd/hook.c
ircd/privilege.c
ircd/s_conf.c
ircd/s_user.c
modules/m_grant.c
modules/m_privs.c
tests/Makefile.am
tests/privilege1.c

Make privsets a little heavier so it's easy to diff them, do that, and fire a hook to inform modules of the changes whenever someone's privset changes. Also add tests.
closes #107

Track privset changes

---

include/channel.h
ircd/channel.c

channel: flood warnings for privmsg, not notice

---

include/messages.h

Reword ERR_ALREADYREGISTERED

---

extensions/override.c

We were trying to delete them from a list they weren't in, and also adding them to the wrong end of the list. Correct both.

Manage override sessions properly

---

help/opers/cmode
help/opers/umode
help/users/umode

Add documenation for +u (bypass filter) channel and user modes.

Document +u in umode and cmode help

---

include/messages.h
include/numeric.h
modules/m_whois.c

Show just the opername if you're an oper the target is not hidden from and you don't have oper:privs.
close #100

m_whois: put opername/privset in RPL_WHOISOPERATOR

---

help/opers/stats
help/users/stats

Add ^ marker to stats l,L

---

extensions/Makefile.am
extensions/cap_oper.c

Per #214. I understand the IRCv3 people might want to get in on this too so we may need to end up changing this depending on how that goes.

Add `solanum.chat/oper` capablity

---

doc/connecting-servers.rst
doc/ircd.conf.example
doc/reference.conf

IMO it's not easy to figure out how to do it from the example and reference config files alone.
This tutorial explains the steps in order and how the different blocks work together.

Add a tutorial for connecting servers and services.

---

doc/reference.conf

Add drain_reason to reference.conf

---

modules/m_services.c

m_services: delete nick delay on RSFNC

---

help/opers/snomask

snomask +F seems to be missing from the help text

add SNO_FARCONNECT to the help text

---

ircd/newconf.c

Also, ignore a connect block that requests certfp authentication without setting the ssl flag, as it will then go on to fail anyway.
Finally, correct an erroneous error message about class blocks.

ircd/newconf: ignore invalid connect block passwords

---

extensions/sasl_usercloak.c

switch sasl_usercloak.c to use SNO_BANNED

---

doc/reference.conf

This was missed in commit 26c3681f7ccece87d9fe

Remove sno_whois from reference.conf

---

doc/features/extban.txt

doc/features/extban.txt: document $j, $x, and $z

---

include/privilege.h
include/s_newconf.h
ircd/s_newconf.c
tests/Makefile.am
tests/misc.c

Support more human friendly k/d/x-line duration format

---

ircd/client.c

show IPs in remote /stats i

---

modules/m_who.c

don't truncate operspy WHO

---

doc/reference.conf
include/client.h
include/s_conf.h
ircd/client.c
ircd/newconf.c
ircd/packet.c
modules/m_info.c

Warn opers about unresponsive servers

---

extensions/extb_extgecos.c

This allows a channel operator to set a channel ban such as `$x:*!*@192.0.2.0/24#*web.libera.chat*` and have it function as intended.

extensions/extb_extgecos: support CIDR masks in $x extbans

---

ircd/s_serv.c
modules/m_services.c

c.f. https://github.com/atheme/atheme/commit/b2b5facd & https://github.com/atheme/atheme/pull/899

support RSFNC indicating type of FNC (e.g. FORCE vs REGAIN)

---

extensions/extb_account.c

To support the draft IRCv3 spec: https://github.com/ircv3/ircv3-specifications/pull/464

Add ACCOUNTEXTBAN ISUPPORT token

---

help/opers/cmode
help/users/cmode

- as per mention of it in #libera by moonmoon 
- maybe there are other additional cmodes not documented, didn't check

document +M cmode

---

ircd/authproc.c

Fix small typo

---

help/opers/challenge
help/opers/join

Reported by joerg on Libera.
Only took 20 years for someone to notice.

Update join and challenge help files.
